---
# Most comments were removed. Check the "slt-netdevops" project
# for additional details about this playbook.
- name: "PLAY 1: Manage NTP configuration"
  hosts: "all"
  tasks:

    # Terraform doesn't have a great "waiting" mechanism, so
    # Ansible can be called right away and then waits 3 minutes
    # for the routers to be fully initialized.
    - name: "Wait for connection"
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 30
        timeout: 180
      delegate_to: localhost

    - name: "TASK 0: Validate NTP server IP addresses"
      assert:
        that:
          - "ntp_server1 is defined"
          - "ntp_server2 is defined"
          - "ntp_server1 | ipv4 == ntp_server1"
          - "ntp_server2 | ipv4 == ntp_server2"
        msg: "Malformed input; please check ntp_server values"

    - name: "TASK 1: Apply NTP updates"
      ios_config:
        lines:
          - "ntp authenticate"
          - "ntp logging"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
      register: "ntp_updates"

    - name: "TASK 2: Print changes if NTP config changed"
      debug:
        var: "ntp_updates.updates"
      when: "ntp_updates.updates is defined"
...
