---
# This is the first play, but rather than define a new play
# and corresponding set of tasks, we import the main NTP
# playbook and pass in some custom NTP servers instead. Using
# static inputs is a good way to "stub out" our variables file
# for the purpose of testing the playbook's logic.
- name: "PLAY 1: Import original playbook with mock NTP servers"
  import_playbook: "ntp_config.yml"
  vars:
    ntp_server1: "203.0.113.1"
    ntp_server2: "203.0.113.2"

# This is the second play. Its purpose is to ensure the
# first play (playbook import) worked correctly. The general
# flow is to ensure the NTP configuration was correctly applied,
# remove the NTP configuration, then ensure the NTP configuration
# was correctly removed. Removal isn't critical, but without it
- name: "PLAY 2: Log into routers to test playbook"
  hosts: "all"
  tasks:

    # This is the first task. It collects information from the
    # router using the "ios_command" module, which is used for
    # non-configuration (exec shell) commands. The command issued
    # returns a table showing each NTP server configured.
    # The output from this command is registered in the
    # variable called "ntp_associations".
    - name: "TASK 1: Gather mock NTP state data after enabling NTP"
      ios_command:
        commands: "show ntp associations"
      register: "ntp_associations"

    # This is the second task. Now that we've registered the router's
    # feedback, we can test it using basic string membership/containment
    # operations. We must ensure that our two mock NTP servers are
    # present in this output. The text output is contained in a subfield
    # called "stdout", and the 0 index is used to represent that this is
    # the output associated with the first (and only) command issued.
    - name: "TASK 2: Ensure that mock NTP servers are present"
      assert:
        that:
          - "'203.0.113.1' in ntp_associations.stdout[0]"
          - "'203.0.113.2' in ntp_associations.stdout[0]"
        msg: "Missing required NTP data:\n{{ ntp_associations.stdout[0] }}"
